# Generated by Django 4.2.9 on 2024-01-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birthdate', models.DateField(null=True)),
                ('passport_ser', models.CharField(max_length=2)),
                ('passport_num', models.CharField(max_length=6)),
            ],
        ),
    ]
